title: Il Mio eCommerce
url: "https://30artgallery.github.io" # Fondamentale per i link della sitemap
baseurl: "/Sito-E-Commerce"

plugins:
  - jekyll-sitemap

collections:
  prodotti:
    output: true
    permalink: /prodotti/:path/
