name: Google Indexing

on:
  push:
    branches:
      - main  # Assicurati che il tuo branch si chiami main (o master)

jobs:
  index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Send URLs to Google
        uses: duc-it/google-indexing-api-action@v1.1.0
        with:
          key: ${{ secrets.INDEXING_SERVICE_ACCOUNT_JSON }}
          sitemap_url: 'https://www.moodhaus.it/sitemap.xml'
